name: aplikasikalkulator
description: "A new Flutter project."

publish_to: 'none' # Prevent publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  math_expressions: ^2.7.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.8.4
  image_picker: ^1.0.7
  path: ^1.8.3
  path_provider: ^2.1.2
  csv: ^5.0.2
  share_plus: ^7.2.1
  file_picker: ^10.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Tambahkan bagian assets dengan benar
  assets:
    - assets/profile.png
    - assets/dual_sense.png
    - assets/compu.png
    - assets/searchim.png